- src: git+https://github.com/wikitops/ansible_docker
  version: "1.7"
  name: docker

- src: git+https://github.com/wikitops/ansible_epel
  version: "1.3"
  name: epel

- src: git+https://github.com/wikitops/ansible_pip
  version: "1.4"
  name: pip
